version: '3.7'
services:
    django:
        container_name: 'django'
        build: ./stripe_assignment
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
        volumes:
            - ./stripe_assignment:/home/stripe_assignment/django
        ports:
            - "8000:8000"
        env_file:
            - ./.env
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
        ports:
            - "5432:5432"

volumes:
    postgres_data:
